# Generated by Django 3.0 on 2023-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'author_book',
            },
        ),
        migrations.CreateModel(
            name='AuthorTable',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'author_table',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('picture', models.URLField()),
                ('introduction', models.TextField()),
                ('datas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
            ],
            options={
                'db_table': 'booklistnew_table',
            },
        ),
    ]
